language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - mvn clean install
addons:
  sonarqube:
    token:
      secure: "o7cgrKj7ihwRlYw3QZOQgO9CYw/1e54zLwvi3jIXwN2ex7dPUSNwpr6t5xBNXb3InQJgnibqFT7Kzqv5kzj1ZMBS9fRK1/6yrNAWc04wNCYPO4D+JbYGgNHbUCllUfce0J03Ee3+yKdQCp9k2lbFJlM4cVnaRuPUk88fK+DqWn4="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
before_deploy:
- export PARA_WAR_FILE=$(find ./target/checkout/para-war/taget -maxdepth 1 -name para-*.war)
deploy:
  provider: releases
  api_key:
    secure: "mYS5XtJsyo674fwe1Ay61Ak2jjjZmeE2cCYte/YHCChWje46ezHYZ3iu/2XmwSXJViZo7Htt8PFkl0XA6zD/TSaHeXeRiuhATmQKPHRsRLax1+VbmExVd3dbOI97TMi+7kguKvlXWA7nwfUZVNsSV/0gmg0LuPTv4vD14UIwPbI="
  file: "${PARA_WAR_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: Erudika/para
